return { -- this table overrides highlights in all themes
  Normal = { bg = "NONE", ctermbg = "NONE" },
  NormalNC = { bg = "NONE", ctermbg = "NONE" },
  NormalFloat = { bg = "NONE", ctermbg = "NONE" },
  FloatBorder = { fg="#111317", bg = "NONE", ctermbg = "NONE" },
  CursorColumn = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
  CursorLine = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
  CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
  LineNr = {},
  SignColumn = {},
  StatusLine = {},
  NeoTreeNormal = { bg = "NONE", ctermbg = "NONE" },
  NeoTreeNormalNC = { bg = "NONE", ctermbg = "NONE" },
  TelescopeNormal = { bg = "NONE", ctermbg = "NONE" },
  TelescopePreviewNormal = { bg = "NONE", ctermbg = "NONE" },
  TelescopePromptNormal = { bg = "NONE", ctermbg = "NONE" },
  TelescopeResultsNormal = { bg = "NONE", ctermbg = "NONE" },
  TabLine = { bg = "NONE", ctermbg = "NONE" },
  TabLineFill = { bg = "NONE", ctermbg = "NONE" },
  VertSplit = { fg="#111317", bg = "NONE", ctermbg = "NONE" },
  WinSeparator = { fg="#111317", bg = "NONE", ctermbg = "NONE" },
  NeoTreeWinSeparator = { fg="#111317", bg = "NONE", ctermbg = "NONE" },
  NeoTreeVertSplit = { fg="#111317", bg = "NONE", ctermbg = "NONE" },
  -- NeoTreeTabInactive = { fg="#494d56", bg = "NONE", ctermbg = "NONE" },
  -- NeoTreeTabActive = { cterm = "bold", gui = "bold", fg = "#adb0bb", bg = "NONE" },
  WinBarNC = { bg = "NONE", ctermbg = "NONE" },
  TelescopePreviewBorder = { fg="#111317", bg = "NONE", ctermbg = "NONE", blend=0 },
  TelescopeResultsBorder = { fg="#111317", bg = "NONE", ctermbg = "NONE", blend=0 },
  TelescopePromptBorder = { fg="#111317", bg = "NONE", ctermbg = "NONE", blend=0 },
  TelescopePromptCounter= { fg="#111317", bg = "NONE", ctermbg = "NONE" },
}
